# Generated by Django 4.2 on 2023-06-04 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='slug')),
                ('message_preview', models.ImageField(blank=True, null=True, upload_to='message_preview/', verbose_name='Превью')),
                ('message_heading', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('date_of_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(default=datetime.date.today, verbose_name='Дата последнего изменения')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
                'ordering': ('message_heading',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('product_category',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Изображение')),
                ('product_price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена за покупку')),
                ('date_of_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(default=datetime.date.today, verbose_name='Дата последнего изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Есть на складе')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукции',
                'ordering': ('product_category',),
            },
        ),
    ]
