# Generated by Django 4.2 on 2023-06-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_version', models.IntegerField(verbose_name='Версия')),
                ('description', models.CharField(max_length=150, verbose_name='Описание версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наличие активной версии')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('product_name',),
            },
        ),
    ]
