# Generated by Django 4.2 on 2023-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='почта_пользователя'),
        ),
    ]
