# Generated by Django 4.2 on 2023-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_is_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта_пользователя'),
        ),
    ]
