# Generated by Django 4.2 on 2023-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_is_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
