# Generated by Django 4.2 on 2023-06-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_is_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_category',), 'permissions': [('set_published_status', 'Can publish post')], 'verbose_name': 'продукция', 'verbose_name_plural': 'продукции'},
        ),
    ]
